version: '2'

services:
  scms_database:
    container_name: scms_database
    image: postgres:9.5-alpine
    ports: [ "15432:5432" ]
    logging:
      driver: "none"
    networks: [ scms-net ]

  scms_web:
    container_name: scms_web
    build: .
    command: bin/rails s --port 3000 -b 0.0.0.0
    volumes: [ .:/app ]
    ports: [ "3001:3000" ]
    depends_on: [ scms_database ]
    networks: [ scms-net ]

networks: 
  scms-net:
    driver: bridge