version: '2'

services:
  scms_database:
    container_name: scms_database
    image: postgres:9.5-alpine
    ports: [ "15432:5432" ]
    networks: [ scms-net ]
    logging:
      driver: "none"

  scms_web:
    container_name: scms_web
    build: .
    command: ruby bin/start
    volumes: [ ".:/app", ".gems:/.gems" ]
    ports: [ "3001:3000" ]
    depends_on: [ scms_database ]
    links: [ scms_database ]
    networks: [ scms-net ]
    environment:
      RAILS_ENV: 'development'

volumes:
  .gems:

networks: 
  scms-net:
    driver: bridge